kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: stq-backend-dev
  name: stq-backend-dev
  namespace: default
  annotations:
    secret.reloader.stakater.com/reload: "tradeenv,couchbase"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: stq-backend-dev
  template:
    metadata:
      labels:
        k8s-app: stq-backend-dev    
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      volumes:
        - name: firebase-adminsdk
          secret:
            secretName: bigquery-admin-sa
      containers:
        - name: stq-backend-dev
          image: gcr.io/xxcloud/stq-backend-dev:e28e82f
          volumeMounts:
            - name: firebase-adminsdk
              mountPath: backend/build/keys
          resources:
            requests:
              cpu: 0.1            
              memory: 312Mi   
            limits:
              cpu: 1            
              memory: 912Mi                               
          env:
            - name: DELAY_SEC
              value: "3"
            - name: DEBUG
              value: "stq*"            
            - name: APP_NAME
              value: "stq"
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: TRADE_ENV
              valueFrom:
                secretKeyRef:
                  name: tradeenv
                  key: TRADE_ENV              
            - name: TZ
              valueFrom:
                secretKeyRef:
                  name: tradeenv
                  key: TZ  
            - name: COUCHBASE_URL
              valueFrom:
                secretKeyRef:
                  name: couchbase
                  key: url      
            - name: COUCHBASE_BUCKET
              valueFrom:
                secretKeyRef:
                  name: couchbase
                  key: bucket
            - name: COUCHBASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: couchbase
                  key: username
            - name: COUCHBASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchbase
                  key: password                                                                                                                                 
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 30    
---
# ------------------- Dashboard Service ------------------- #
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: stq-backend-dev
  name: stq-backend-dev
  namespace: default
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    k8s-app: stq-backend-dev
